export const seasonings = [
  "Allspice",
  "Basil",
  "Bay Leaf",
  "Black Pepper",
  "Cajun Seasoning",
  "Cardamom",
  "Cayenne Pepper",
  "Celery Salt",
  "Chili Powder",
  "Chinese Five Spice",
  "Chipotle Powder",
  "Cilantro",
  "Cinnamon",
  "Cloves",
  "Coriander",
  "Cream of Tartar",
  "Cumin",
  "Curry Powder",
  "Dill",
  "Fennel",
  "Garam Masala",
  "Garlic Powder",
  "Garlic Salt",
  "Ground Ginger",
  "Italian Seasoning",
  "Lemon Pepper",
  "Marjoram",
  "Mustard Powder",
  "Nutmeg",
  "Onion Powder",
  "Oregano",
  "Paprika",
  "Parsley",
  "Pumpkin Spice",
  "Red Pepper Flakes",
  "Rosemary",
  "Saffron",
  "Sage",
  "Seasoned Salt",
  "Sesame Seeds",
  "Smoked Paprika",
  "Star Anise",
  "Sumac",
  "Taco Seasoning",
  "Tarragon",
  "Thyme",
  "Turmeric",
  "Vanilla Extract",
  "White Pepper",
];
